"""The routing tables in the docs must match what the registry answers.

Every routing table in ``docs/content/kernels/*.md`` says it is "generated by
probing the kernels" -- but the fences are checked-in text, and checked-in
text is a second copy of the routing rules. The second copy is the one that
goes stale; that is the exact failure the kernel registry exists to remove
(an error message advised "use softmax_columns for width >= 128" long after
the boundary had moved to 65).

This is fully generic across every doc page and every operation: each
routing table is preceded by an HTML comment declaring the exact
``boundaries()`` call that produced it --

    <!-- doc-routing-check: op="softmax" param="shape" label="n"
         values="range(1,140)" build="lambda n: (8, n)" dim=1 -->
    ```
    n 1..127                     softmax_rows_partial
    ...
    ```

-- so this test discovers every marker in every doc page, re-runs its
declared ``boundaries()`` call, and asserts the rendered output is *exactly*
the checked-in fence text. Adding a new op's doc page needs no change here:
write the table, add its marker with the params that produced it, done.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest

from ipu_apps.kernel_registry import boundaries

# Runfiles and a plain checkout put the docs in the same place relative to
# the repo root, so walk up from this file until the kernels dir appears.
_KERNELS_DIR = None
for _parent in Path(__file__).resolve().parents:
    _candidate = _parent / "docs/content/kernels"
    if _candidate.is_dir():
        _KERNELS_DIR = _candidate
        break

_DOC_PAGES = sorted(_KERNELS_DIR.glob("*.md")) if _KERNELS_DIR else []

# A marker plus the fenced block immediately following it (blank lines
# between the comment and the fence are tolerated).
_MARKER_AND_FENCE = re.compile(
    r"<!--\s*doc-routing-check:\s*(?P<attrs>.*?)-->\s*\n+"
    r"```[^\n]*\n(?P<body>.*?)^```",
    re.S | re.M,
)

# One `key="value"` or `key=value` (unquoted for numeric/bare-word values)
# pair inside a marker's attribute string.
_ATTR = re.compile(r'(\w+)=(?:"([^"]*)"|(\S+))')

# Names a marker's `values=`/`build=` expressions are allowed to use. Nothing
# else is reachable from an evaluated marker -- these are checked-in doc
# files, not user input, but there is no reason to give them a bigger
# namespace than `range` and a one-line `lambda`.
_SAFE_EVAL_NAMES = {"range": range}


def _parse_marker(attrs_text: str) -> dict[str, Any]:
    parsed: dict[str, str] = {}
    for match in _ATTR.finditer(attrs_text):
        key = match.group(1)
        raw = match.group(2) if match.group(2) is not None else match.group(3)
        parsed[key] = raw

    kwargs: dict[str, Any] = {}
    for key, raw in parsed.items():
        if key in ("op", "param", "label"):
            kwargs[key] = raw
        elif key in ("values", "build"):
            kwargs[key] = eval(raw, {"__builtins__": {}}, _SAFE_EVAL_NAMES)
        else:
            # Every other attribute is a fixed kwarg for boundaries()/resolve()
            # (e.g. dim=1, in_channels=8, has_bias=False) -- Python literals.
            kwargs[key] = eval(raw, {"__builtins__": {}}, {})
    return kwargs


def _documented_tables() -> list[tuple[Path, dict[str, Any], str]]:
    """Every ``(doc_path, boundaries_kwargs, checked_in_fence_text)`` triple."""
    tables = []
    for doc in _DOC_PAGES:
        text = doc.read_text()
        for match in _MARKER_AND_FENCE.finditer(text):
            kwargs = _parse_marker(match["attrs"])
            tables.append((doc, kwargs, match["body"]))
    return tables


_TABLES = _documented_tables()

pytestmark = pytest.mark.skipif(
    not _DOC_PAGES, reason="docs/content/kernels/ is not in the runfiles"
)


def test_doc_pages_actually_contain_routing_tables():
    """Guards the parser: a doc rewrite that drops the markers must not turn
    this file into a test that silently checks nothing. Not every page in
    docs/content/kernels/ has a routing table (index.md is a landing page),
    so this only guards the total, not per-page coverage."""
    assert len(_TABLES) >= 6, f"parsed only {len(_TABLES)} routing tables from {_DOC_PAGES}"
    covered = {doc.name for doc, _, _ in _TABLES}
    assert {"softmax.md", "convolutions.md"} <= covered, (
        f"expected routing tables from softmax.md and convolutions.md, "
        f"only found tables in: {covered}"
    )


@pytest.mark.parametrize(
    "doc,kwargs,expected",
    _TABLES,
    ids=[f"{doc.name}:{kwargs.get('op')}:{kwargs.get('label')}" for doc, kwargs, _ in _TABLES],
)
def test_documented_table_matches_the_registry(doc, kwargs, expected):
    op = kwargs.pop("op")
    param = kwargs.pop("param")
    label = kwargs.pop("label")
    values = kwargs.pop("values")
    build = kwargs.pop("build", None)

    rendered = "\n".join(
        b.render(label) for b in boundaries(op, param, values, build=build, **kwargs)
    )
    assert rendered == expected.rstrip("\n"), (
        f"{doc.name}'s {op}/{label} table no longer matches what the registry "
        f"answers. Re-probe it (see the marker comment above the fence) and "
        f"update the checked-in table.\n\n--- registry says ---\n{rendered}\n"
        f"--- doc says ---\n{expected.rstrip(chr(10))}"
    )
