"""Prototyping mode: opt-in shortcuts that are not a faithful chip model.

The default emulator models what the hardware does, cycle by cycle and slot by
slot: every slot is dispatched even when it holds a NOP, every multiply applies
its element mask, every cycle takes a full register snapshot. That fidelity is
the point — it is what makes the emulator answerable about the chip.

Prototyping mode trades some of it for speed on long runs (a full-image
convolution, a sweep over shapes) where the question is "what does this kernel
compute" rather than "what does the chip do". Its shortcuts are:

* provably result-preserving — the state after every cycle is **bit-identical**
  to the faithful path, and ``test_prototyping_equivalence.py`` pins registers,
  XMEM, exceptions, and snapshots including batched full-row FP32 activations;
  and
* **not** a description of the hardware — a skipped NOP slot still occupies its
  slot in the real machine, and a skipped mask is still applied there.

So it is safe to trust the numbers a prototyping run produces, and wrong to
reason from it about what the chip spends a cycle on.

The Bazel build flag is a mandatory capability gate:

1. ``bazel run --define=ipu_proto=1 //...`` generates ``_build_flags.py`` with
   prototyping support enabled and makes it the default;
2. inside that flagged build, ``IpuState(prototyping=...)`` may select the mode
   per state; and
3. inside that flagged build, ``IPU_EMU_PROTOTYPING`` may select the process
   default.

A build without the flag, including a plain checkout, cannot activate the fast
paths. A positive runtime request in such a build raises ``ValueError``.
"""

from __future__ import annotations

import os

try:  # generated by the Bazel genrule; absent in a plain checkout
    from ipu_emu._build_flags import PROTOTYPING as _BUILD_DEFAULT
except ImportError:  # pragma: no cover - depends on the build, not the code
    _BUILD_DEFAULT = False

_FALSEY = {"", "0", "false", "False", "no", "off"}


def default_enabled() -> bool:
    """Whether a new :class:`~ipu_emu.ipu_state.IpuState` starts in prototyping mode."""
    env = os.environ.get("IPU_EMU_PROTOTYPING")
    requested = bool(_BUILD_DEFAULT) if env is None else env not in _FALSEY
    return resolve_enabled(requested)


def build_enabled() -> bool:
    """Whether this build is allowed to execute prototyping fast paths."""
    return bool(_BUILD_DEFAULT)


def resolve_enabled(requested: bool | None) -> bool:
    """Resolve a per-state request without allowing it to bypass the build gate."""
    if requested is None:
        return default_enabled()
    enabled = bool(requested)
    if enabled and not build_enabled():
        raise ValueError(
            "prototyping mode requires a Bazel build with --define=ipu_proto=1"
        )
    return enabled
